# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BehavioralMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BehavioralMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBehavioralMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BehavioralMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BehavioralMessage
    def StudentName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BehavioralMessage
    def RoomId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BehavioralMessage
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BehavioralMessage
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BehavioralMessage
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BehavioralMessage
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # BehavioralMessage
    def ClientTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BehavioralMessageStart(builder):
    builder.StartObject(7)

def Start(builder):
    BehavioralMessageStart(builder)

def BehavioralMessageAddStudentName(builder, studentName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(studentName), 0)

def AddStudentName(builder, studentName):
    BehavioralMessageAddStudentName(builder, studentName)

def BehavioralMessageAddRoomId(builder, roomId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(roomId), 0)

def AddRoomId(builder, roomId):
    BehavioralMessageAddRoomId(builder, roomId)

def BehavioralMessageAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder, sessionId):
    BehavioralMessageAddSessionId(builder, sessionId)

def BehavioralMessageAddEventType(builder, eventType):
    builder.PrependInt8Slot(3, eventType, 0)

def AddEventType(builder, eventType):
    BehavioralMessageAddEventType(builder, eventType)

def BehavioralMessageAddDataType(builder, dataType):
    builder.PrependUint8Slot(4, dataType, 0)

def AddDataType(builder, dataType):
    BehavioralMessageAddDataType(builder, dataType)

def BehavioralMessageAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    BehavioralMessageAddData(builder, data)

def BehavioralMessageAddClientTimestamp(builder, clientTimestamp):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(clientTimestamp), 0)

def AddClientTimestamp(builder, clientTimestamp):
    BehavioralMessageAddClientTimestamp(builder, clientTimestamp)

def BehavioralMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return BehavioralMessageEnd(builder)
