# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CopyPasteEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CopyPasteEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCopyPasteEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CopyPasteEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CopyPasteEvent
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CopyPasteEvent
    def ContentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CopyPasteEvent
    def ContentPreview(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CopyPasteEvent
    def WidgetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CopyPasteEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CopyPasteEventStart(builder):
    builder.StartObject(5)

def Start(builder):
    CopyPasteEventStart(builder)

def CopyPasteEventAddAction(builder, action):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(action), 0)

def AddAction(builder, action):
    CopyPasteEventAddAction(builder, action)

def CopyPasteEventAddContentLength(builder, contentLength):
    builder.PrependInt32Slot(1, contentLength, 0)

def AddContentLength(builder, contentLength):
    CopyPasteEventAddContentLength(builder, contentLength)

def CopyPasteEventAddContentPreview(builder, contentPreview):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(contentPreview), 0)

def AddContentPreview(builder, contentPreview):
    CopyPasteEventAddContentPreview(builder, contentPreview)

def CopyPasteEventAddWidgetId(builder, widgetId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(widgetId), 0)

def AddWidgetId(builder, widgetId):
    CopyPasteEventAddWidgetId(builder, widgetId)

def CopyPasteEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    CopyPasteEventAddTimestamp(builder, timestamp)

def CopyPasteEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return CopyPasteEventEnd(builder)
