# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

class EventData(object):
    NONE = 0
    KeyPressEvent = 1
    MouseMoveEvent = 2
    MouseClickEvent = 3
    MouseEnterEvent = 4
    MouseLeaveEvent = 5
    FocusInEvent = 6
    FocusOutEvent = 7
    CopyPasteEvent = 8
    WindowSwitchEvent = 9
    ScrollEvent = 10
    ExamEvent = 11
