# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

class EventType(object):
    KeyPress = 0
    MouseMove = 1
    MouseClick = 2
    CopyPaste = 3
    WindowSwitch = 4
    Scroll = 5
    ExamEvent = 6
    MouseEnter = 7
    MouseLeave = 8
    FocusIn = 9
    FocusOut = 10
