# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExamEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExamEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExamEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExamEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExamEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExamEvent
    def Details(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ExamEvent
    def DetailsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExamEvent
    def DetailsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ExamEvent
    def Subject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExamEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ExamEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    ExamEventStart(builder)

def ExamEventAddEventType(builder, eventType):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventType), 0)

def AddEventType(builder, eventType):
    ExamEventAddEventType(builder, eventType)

def ExamEventAddDetails(builder, details):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(details), 0)

def AddDetails(builder, details):
    ExamEventAddDetails(builder, details)

def ExamEventStartDetailsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDetailsVector(builder, numElems):
    return ExamEventStartDetailsVector(builder, numElems)

def ExamEventCreateDetailsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateDetailsVector(builder, data):
    ExamEventCreateDetailsVector(builder, data)

def ExamEventAddSubject(builder, subject):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(subject), 0)

def AddSubject(builder, subject):
    ExamEventAddSubject(builder, subject)

def ExamEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    ExamEventAddTimestamp(builder, timestamp)

def ExamEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExamEventEnd(builder)
