# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FocusOutEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FocusOutEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFocusOutEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FocusOutEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FocusOutEvent
    def WidgetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FocusOutEvent
    def CurrentValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FocusOutEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FocusOutEventStart(builder):
    builder.StartObject(3)

def Start(builder):
    FocusOutEventStart(builder)

def FocusOutEventAddWidgetId(builder, widgetId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetId), 0)

def AddWidgetId(builder, widgetId):
    FocusOutEventAddWidgetId(builder, widgetId)

def FocusOutEventAddCurrentValue(builder, currentValue):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(currentValue), 0)

def AddCurrentValue(builder, currentValue):
    FocusOutEventAddCurrentValue(builder, currentValue)

def FocusOutEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    FocusOutEventAddTimestamp(builder, timestamp)

def FocusOutEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return FocusOutEventEnd(builder)
