# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KeyPressEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KeyPressEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKeyPressEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KeyPressEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KeyPressEvent
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyPressEvent
    def WidgetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyPressEvent
    def TextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # KeyPressEvent
    def Modifiers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyPressEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KeyPressEventStart(builder):
    builder.StartObject(5)

def Start(builder):
    KeyPressEventStart(builder)

def KeyPressEventAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    KeyPressEventAddKey(builder, key)

def KeyPressEventAddWidgetId(builder, widgetId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(widgetId), 0)

def AddWidgetId(builder, widgetId):
    KeyPressEventAddWidgetId(builder, widgetId)

def KeyPressEventAddTextLength(builder, textLength):
    builder.PrependInt32Slot(2, textLength, 0)

def AddTextLength(builder, textLength):
    KeyPressEventAddTextLength(builder, textLength)

def KeyPressEventAddModifiers(builder, modifiers):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(modifiers), 0)

def AddModifiers(builder, modifiers):
    KeyPressEventAddModifiers(builder, modifiers)

def KeyPressEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    KeyPressEventAddTimestamp(builder, timestamp)

def KeyPressEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return KeyPressEventEnd(builder)
