# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MouseClickEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MouseClickEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMouseClickEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MouseClickEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MouseClickEvent
    def ButtonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseClickEvent
    def HoverDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MouseClickEvent
    def ButtonText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseClickEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MouseClickEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    MouseClickEventStart(builder)

def MouseClickEventAddButtonId(builder, buttonId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buttonId), 0)

def AddButtonId(builder, buttonId):
    MouseClickEventAddButtonId(builder, buttonId)

def MouseClickEventAddHoverDurationMs(builder, hoverDurationMs):
    builder.PrependInt32Slot(1, hoverDurationMs, 0)

def AddHoverDurationMs(builder, hoverDurationMs):
    MouseClickEventAddHoverDurationMs(builder, hoverDurationMs)

def MouseClickEventAddButtonText(builder, buttonText):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buttonText), 0)

def AddButtonText(builder, buttonText):
    MouseClickEventAddButtonText(builder, buttonText)

def MouseClickEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    MouseClickEventAddTimestamp(builder, timestamp)

def MouseClickEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return MouseClickEventEnd(builder)
