# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MouseMoveEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MouseMoveEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMouseMoveEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MouseMoveEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MouseMoveEvent
    def WidgetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseMoveEvent
    def HoverDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MouseMoveEvent
    def CurrentValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseMoveEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MouseMoveEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    MouseMoveEventStart(builder)

def MouseMoveEventAddWidgetId(builder, widgetId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetId), 0)

def AddWidgetId(builder, widgetId):
    MouseMoveEventAddWidgetId(builder, widgetId)

def MouseMoveEventAddHoverDurationMs(builder, hoverDurationMs):
    builder.PrependInt32Slot(1, hoverDurationMs, 0)

def AddHoverDurationMs(builder, hoverDurationMs):
    MouseMoveEventAddHoverDurationMs(builder, hoverDurationMs)

def MouseMoveEventAddCurrentValue(builder, currentValue):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(currentValue), 0)

def AddCurrentValue(builder, currentValue):
    MouseMoveEventAddCurrentValue(builder, currentValue)

def MouseMoveEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    MouseMoveEventAddTimestamp(builder, timestamp)

def MouseMoveEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return MouseMoveEventEnd(builder)
