# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MouseLeaveEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MouseLeaveEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMouseLeaveEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MouseLeaveEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MouseLeaveEvent
    def WidgetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseLeaveEvent
    def HoverDurationMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MouseLeaveEvent
    def CurrentValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MouseLeaveEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MouseLeaveEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    MouseLeaveEventStart(builder)

def MouseLeaveEventAddWidgetId(builder, widgetId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetId), 0)

def AddWidgetId(builder, widgetId):
    MouseLeaveEventAddWidgetId(builder, widgetId)

def MouseLeaveEventAddHoverDurationMs(builder, hoverDurationMs):
    builder.PrependInt32Slot(1, hoverDurationMs, 0)

def AddHoverDurationMs(builder, hoverDurationMs):
    MouseLeaveEventAddHoverDurationMs(builder, hoverDurationMs)

def MouseLeaveEventAddCurrentValue(builder, currentValue):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(currentValue), 0)

def AddCurrentValue(builder, currentValue):
    MouseLeaveEventAddCurrentValue(builder, currentValue)

def MouseLeaveEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    MouseLeaveEventAddTimestamp(builder, timestamp)

def MouseLeaveEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return MouseLeaveEventEnd(builder)
