# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScrollEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScrollEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScrollEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScrollEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScrollEvent
    def AreaId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScrollEvent
    def ScrollValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScrollEvent
    def SpeedPxS(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ScrollEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ScrollEventStart(builder):
    builder.StartObject(4)

def Start(builder):
    ScrollEventStart(builder)

def ScrollEventAddAreaId(builder, areaId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(areaId), 0)

def AddAreaId(builder, areaId):
    ScrollEventAddAreaId(builder, areaId)

def ScrollEventAddScrollValue(builder, scrollValue):
    builder.PrependInt32Slot(1, scrollValue, 0)

def AddScrollValue(builder, scrollValue):
    ScrollEventAddScrollValue(builder, scrollValue)

def ScrollEventAddSpeedPxS(builder, speedPxS):
    builder.PrependFloat32Slot(2, speedPxS, 0.0)

def AddSpeedPxS(builder, speedPxS):
    ScrollEventAddSpeedPxS(builder, speedPxS)

def ScrollEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    ScrollEventAddTimestamp(builder, timestamp)

def ScrollEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScrollEventEnd(builder)
