# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Behavioral

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WindowSwitchEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WindowSwitchEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWindowSwitchEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WindowSwitchEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WindowSwitchEvent
    def PreviousWindow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WindowSwitchEvent
    def CurrentWindow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WindowSwitchEvent
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WindowSwitchEventStart(builder):
    builder.StartObject(3)

def Start(builder):
    WindowSwitchEventStart(builder)

def WindowSwitchEventAddPreviousWindow(builder, previousWindow):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(previousWindow), 0)

def AddPreviousWindow(builder, previousWindow):
    WindowSwitchEventAddPreviousWindow(builder, previousWindow)

def WindowSwitchEventAddCurrentWindow(builder, currentWindow):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(currentWindow), 0)

def AddCurrentWindow(builder, currentWindow):
    WindowSwitchEventAddCurrentWindow(builder, currentWindow)

def WindowSwitchEventAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    WindowSwitchEventAddTimestamp(builder, timestamp)

def WindowSwitchEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return WindowSwitchEventEnd(builder)
