# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AbsentDetection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AbsentDetection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAbsentDetection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AbsentDetection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AbsentDetection
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AbsentDetection
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AbsentDetection
    def MzScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AbsentDetection
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AbsentDetection
    def DetectionCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AbsentDetection
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AbsentDetectionStart(builder):
    builder.StartObject(6)

def Start(builder):
    AbsentDetectionStart(builder)

def AbsentDetectionAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    AbsentDetectionAddUsername(builder, username)

def AbsentDetectionAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def AddValue(builder, value):
    AbsentDetectionAddValue(builder, value)

def AbsentDetectionAddMzScore(builder, mzScore):
    builder.PrependFloat32Slot(2, mzScore, 0.0)

def AddMzScore(builder, mzScore):
    AbsentDetectionAddMzScore(builder, mzScore)

def AbsentDetectionAddSeverity(builder, severity):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(severity), 0)

def AddSeverity(builder, severity):
    AbsentDetectionAddSeverity(builder, severity)

def AbsentDetectionAddDetectionCount(builder, detectionCount):
    builder.PrependInt32Slot(4, detectionCount, 0)

def AddDetectionCount(builder, detectionCount):
    AbsentDetectionAddDetectionCount(builder, detectionCount)

def AbsentDetectionAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    AbsentDetectionAddTimestamp(builder, timestamp)

def AbsentDetectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return AbsentDetectionEnd(builder)
