# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttentionData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttentionData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttentionData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttentionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttentionData
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AttentionData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttentionData
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AttentionDataStart(builder):
    builder.StartObject(3)

def Start(builder):
    AttentionDataStart(builder)

def AttentionDataAddValue(builder, value):
    builder.PrependFloat32Slot(0, value, 0.0)

def AddValue(builder, value):
    AttentionDataAddValue(builder, value)

def AttentionDataAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    AttentionDataAddTimestamp(builder, timestamp)

def AttentionDataAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    AttentionDataAddUsername(builder, username)

def AttentionDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttentionDataEnd(builder)
