# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttentionAnalysis(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttentionAnalysis()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttentionAnalysis(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttentionAnalysis
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttentionAnalysis
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttentionAnalysis
    def Room(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttentionAnalysis
    def Students(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # AttentionAnalysis
    def StudentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AttentionAnalysis
    def StudentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # AttentionAnalysis
    def AttentionValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AttentionAnalysis
    def AttentionValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # AttentionAnalysis
    def AttentionValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AttentionAnalysis
    def AttentionValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # AttentionAnalysis
    def AvgPercentage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AttentionAnalysis
    def StudentCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AttentionAnalysis
    def AbsentMinded(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Attention.AbsentDetection import AbsentDetection
            obj = AbsentDetection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AttentionAnalysis
    def AbsentMindedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AttentionAnalysis
    def AbsentMindedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # AttentionAnalysis
    def LowAttention(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Attention.LowAttentionDetection import LowAttentionDetection
            obj = LowAttentionDetection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AttentionAnalysis
    def LowAttentionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AttentionAnalysis
    def LowAttentionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def AttentionAnalysisStart(builder):
    builder.StartObject(8)

def Start(builder):
    AttentionAnalysisStart(builder)

def AttentionAnalysisAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    AttentionAnalysisAddTimestamp(builder, timestamp)

def AttentionAnalysisAddRoom(builder, room):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(room), 0)

def AddRoom(builder, room):
    AttentionAnalysisAddRoom(builder, room)

def AttentionAnalysisAddStudents(builder, students):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(students), 0)

def AddStudents(builder, students):
    AttentionAnalysisAddStudents(builder, students)

def AttentionAnalysisStartStudentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStudentsVector(builder, numElems):
    return AttentionAnalysisStartStudentsVector(builder, numElems)

def AttentionAnalysisCreateStudentsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateStudentsVector(builder, data):
    AttentionAnalysisCreateStudentsVector(builder, data)

def AttentionAnalysisAddAttentionValues(builder, attentionValues):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(attentionValues), 0)

def AddAttentionValues(builder, attentionValues):
    AttentionAnalysisAddAttentionValues(builder, attentionValues)

def AttentionAnalysisStartAttentionValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttentionValuesVector(builder, numElems):
    return AttentionAnalysisStartAttentionValuesVector(builder, numElems)

def AttentionAnalysisCreateAttentionValuesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateAttentionValuesVector(builder, data):
    AttentionAnalysisCreateAttentionValuesVector(builder, data)

def AttentionAnalysisAddAvgPercentage(builder, avgPercentage):
    builder.PrependFloat32Slot(4, avgPercentage, 0.0)

def AddAvgPercentage(builder, avgPercentage):
    AttentionAnalysisAddAvgPercentage(builder, avgPercentage)

def AttentionAnalysisAddStudentCount(builder, studentCount):
    builder.PrependInt32Slot(5, studentCount, 0)

def AddStudentCount(builder, studentCount):
    AttentionAnalysisAddStudentCount(builder, studentCount)

def AttentionAnalysisAddAbsentMinded(builder, absentMinded):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(absentMinded), 0)

def AddAbsentMinded(builder, absentMinded):
    AttentionAnalysisAddAbsentMinded(builder, absentMinded)

def AttentionAnalysisStartAbsentMindedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAbsentMindedVector(builder, numElems):
    return AttentionAnalysisStartAbsentMindedVector(builder, numElems)

def AttentionAnalysisCreateAbsentMindedVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateAbsentMindedVector(builder, data):
    AttentionAnalysisCreateAbsentMindedVector(builder, data)

def AttentionAnalysisAddLowAttention(builder, lowAttention):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(lowAttention), 0)

def AddLowAttention(builder, lowAttention):
    AttentionAnalysisAddLowAttention(builder, lowAttention)

def AttentionAnalysisStartLowAttentionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLowAttentionVector(builder, numElems):
    return AttentionAnalysisStartLowAttentionVector(builder, numElems)

def AttentionAnalysisCreateLowAttentionVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateLowAttentionVector(builder, data):
    AttentionAnalysisCreateLowAttentionVector(builder, data)

def AttentionAnalysisEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttentionAnalysisEnd(builder)
