# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAudioMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AudioMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioMessage
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AudioMessage
    def Filename(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AudioMessage
    def FileData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # AudioMessage
    def FileDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # AudioMessage
    def FileDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AudioMessage
    def FileDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def AudioMessageStart(builder):
    builder.StartObject(3)

def Start(builder):
    AudioMessageStart(builder)

def AudioMessageAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    AudioMessageAddUsername(builder, username)

def AudioMessageAddFilename(builder, filename):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(filename), 0)

def AddFilename(builder, filename):
    AudioMessageAddFilename(builder, filename)

def AudioMessageAddFileData(builder, fileData):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fileData), 0)

def AddFileData(builder, fileData):
    AudioMessageAddFileData(builder, fileData)

def AudioMessageStartFileDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartFileDataVector(builder, numElems):
    return AudioMessageStartFileDataVector(builder, numElems)

def AudioMessageCreateFileDataVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependInt8(item)
    return builder.EndVector()

def CreateFileDataVector(builder, data):
    AudioMessageCreateFileDataVector(builder, data)

def AudioMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return AudioMessageEnd(builder)
