# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HandRaise(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandRaise()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandRaise(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandRaise
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandRaise
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HandRaise
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HandRaiseStart(builder):
    builder.StartObject(2)

def Start(builder):
    HandRaiseStart(builder)

def HandRaiseAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    HandRaiseAddUsername(builder, username)

def HandRaiseAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    HandRaiseAddTimestamp(builder, timestamp)

def HandRaiseEnd(builder):
    return builder.EndObject()

def End(builder):
    return HandRaiseEnd(builder)
