# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoginResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoginResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoginResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoginResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoginResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginResponse
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginResponse
    def Room(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginResponse
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LoginResponseStart(builder):
    builder.StartObject(5)

def Start(builder):
    LoginResponseStart(builder)

def LoginResponseAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    LoginResponseAddStatus(builder, status)

def LoginResponseAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    LoginResponseAddMessage(builder, message)

def LoginResponseAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    LoginResponseAddUsername(builder, username)

def LoginResponseAddRoom(builder, room):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(room), 0)

def AddRoom(builder, room):
    LoginResponseAddRoom(builder, room)

def LoginResponseAddRole(builder, role):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(role), 0)

def AddRole(builder, role):
    LoginResponseAddRole(builder, role)

def LoginResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return LoginResponseEnd(builder)
