# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoginRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoginRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoginRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoginRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoginRequest
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginRequest
    def Room(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoginRequest
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LoginRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    LoginRequestStart(builder)

def LoginRequestAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    LoginRequestAddToken(builder, token)

def LoginRequestAddRoom(builder, room):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(room), 0)

def AddRoom(builder, room):
    LoginRequestAddRoom(builder, room)

def LoginRequestAddRole(builder, role):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(role), 0)

def AddRole(builder, role):
    LoginRequestAddRole(builder, role)

def LoginRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return LoginRequestEnd(builder)
