# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LowAttentionDetection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LowAttentionDetection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLowAttentionDetection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LowAttentionDetection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LowAttentionDetection
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LowAttentionDetection
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LowAttentionDetection
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LowAttentionDetection
    def DetectionCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LowAttentionDetection
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LowAttentionDetectionStart(builder):
    builder.StartObject(5)

def Start(builder):
    LowAttentionDetectionStart(builder)

def LowAttentionDetectionAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    LowAttentionDetectionAddUsername(builder, username)

def LowAttentionDetectionAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def AddValue(builder, value):
    LowAttentionDetectionAddValue(builder, value)

def LowAttentionDetectionAddSeverity(builder, severity):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(severity), 0)

def AddSeverity(builder, severity):
    LowAttentionDetectionAddSeverity(builder, severity)

def LowAttentionDetectionAddDetectionCount(builder, detectionCount):
    builder.PrependInt32Slot(3, detectionCount, 0)

def AddDetectionCount(builder, detectionCount):
    LowAttentionDetectionAddDetectionCount(builder, detectionCount)

def LowAttentionDetectionAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    LowAttentionDetectionAddTimestamp(builder, timestamp)

def LowAttentionDetectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return LowAttentionDetectionEnd(builder)
