# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

class Message(object):
    NONE = 0
    LoginRequest = 1
    LoginResponse = 2
    AttentionData = 3
    AttentionAnalysis = 4
    AudioMessage = 5
    PermissionRequest = 6
    PermissionResponse = 7
    HandRaise = 8
    TextMessage = 9
