# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PermissionResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PermissionResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPermissionResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PermissionResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PermissionResponse
    def Accept(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PermissionResponse
    def Countdown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PermissionResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    PermissionResponseStart(builder)

def PermissionResponseAddAccept(builder, accept):
    builder.PrependBoolSlot(0, accept, 0)

def AddAccept(builder, accept):
    PermissionResponseAddAccept(builder, accept)

def PermissionResponseAddCountdown(builder, countdown):
    builder.PrependInt32Slot(1, countdown, 0)

def AddCountdown(builder, countdown):
    PermissionResponseAddCountdown(builder, countdown)

def PermissionResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return PermissionResponseEnd(builder)
