# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PermissionRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PermissionRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPermissionRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PermissionRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PermissionRequest
    def Student(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PermissionRequest
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PermissionRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    PermissionRequestStart(builder)

def PermissionRequestAddStudent(builder, student):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(student), 0)

def AddStudent(builder, student):
    PermissionRequestAddStudent(builder, student)

def PermissionRequestAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    PermissionRequestAddTimestamp(builder, timestamp)

def PermissionRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return PermissionRequestEnd(builder)
