# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StudentAttention(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StudentAttention()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStudentAttention(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StudentAttention
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StudentAttention
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentAttention
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def StudentAttentionStart(builder):
    builder.StartObject(2)

def Start(builder):
    StudentAttentionStart(builder)

def StudentAttentionAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    StudentAttentionAddUsername(builder, username)

def StudentAttentionAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def AddValue(builder, value):
    StudentAttentionAddValue(builder, value)

def StudentAttentionEnd(builder):
    return builder.EndObject()

def End(builder):
    return StudentAttentionEnd(builder)
