# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Attention

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TextMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextMessage
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TextMessage
    def Content(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TextMessage
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TextMessageStart(builder):
    builder.StartObject(3)

def Start(builder):
    TextMessageStart(builder)

def TextMessageAddUsername(builder, username):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)

def AddUsername(builder, username):
    TextMessageAddUsername(builder, username)

def TextMessageAddContent(builder, content):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder, content):
    TextMessageAddContent(builder, content)

def TextMessageAddTimestamp(builder, timestamp):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    TextMessageAddTimestamp(builder, timestamp)

def TextMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextMessageEnd(builder)
